#!/bin/bash
echo "Deploying to Vercel..."
echo "Project: govori-academy-landing"
echo "Files ready:"
echo "- index.html ✓"
echo "- css/styles.css ✓"
echo "- js/script.js ✓"
echo ""
echo "GitHub repository: https://github.com/MonsterDEVZ/govori-academy-landing"
echo ""
echo "To complete deployment, please:"
echo "1. Go to https://vercel.com/dashboard"
echo "2. Click 'Import Project'"
echo "3. Import from GitHub: MonsterDEVZ/govori-academy-landing"
echo "4. Click 'Deploy'"
echo ""
echo "Or authorize Vercel CLI:"
echo "https://vercel.com/oauth/device?user_code=XKNT-BRHM"
